name: synca src.gen

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.6.20318.15
    - name: Install dependencies
      run: dotnet restore src/synca.gen/synca.gen.csproj
    - name: Build
      run: dotnet build src/synca.gen/synca.gen.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
